keepInventoryModule: true
deepslateInstabreakModule: true
playerHeadDropsModule: true
noMendingTradeModule: true
noCropTrampleModule: true
huskDropsSandModule: true
snowballFightModule: true
invisibleItemFramesModule: true
antiCreeperGriefModule: true
antiEndermanGriefModule: true
antiGhastGriefModule: true