keepInventoryModule: true
deepslateInstabreakModule: true
playerHeadDropsModule: true
noMendingTradeModule: true
noCropTrampleModule: true
huskDropsSandModule: true
snowballFightModule: true
invisibleItemFramesModule: true
antiCreeperGriefModule: true
antiEndermanGriefModule: true
antiGhastGriefModule: true
antiRavagerGriefModule: true
husksReplacedPyramidModule : true
stableHorseModule: true
customAttributeModule: true

# Controls for how long a mob will be immune to hard despawn right after going through a portal.
# All times in this config are in seconds
default-despawn-immunity-time-seconds: 20

# Immunity duration overrides per mob type.
# Valid mob types: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/EntityType.html
despawn-immunity-time-overrides:
  piglin: 40
  iron_golem: 40
  guardian: 90